name: i18n

on:
  push:
  pull_request:
    branches: [main]

jobs:
  i18n:
    name: i18n
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Clean Install
        run: npm ci && npm run build
      - name: i18n translate
        run: npx @inlang/cli machine translate --project ./project.inlang
